export type CompanyType = (typeof COMPANIES)[number];

export const COMPANIES = [
	{
		title: "Software Engineer",
		company: "Syntroper",
		image: "syntroper",
		url: "https://www.syntroper.ai/",
		city: "Auckland",
		state: "North Island",
		startDate: "2025-08-01",
		endDate: undefined,
	},
	{
		title: "Design Engineer",
		company: "CyberBrokers",
		image: "cyberbrokers",
		url: "https://www.cyberbrokers.com/",
		city: "Chicago",
		state: "Illinois",
		startDate: "2023-05-15",
		endDate: "2025-07-31",
	},
	{
		title: "Software Engineer",
		company: "Blockade Games",
		image: "blockade",
		url: "https://blockade.games/",
		city: "Indianapolis",
		state: "Indiana",
		startDate: "2021-12-01",
		endDate: "2023-04-28",
	},
	{
		title: "Front End Engineer",
		company: "Invillia",
		image: "invillia",
		url: "https://invillia.com/",
		city: "Araraquara",
		state: "São Paulo",
		startDate: "2022-05-10",
		endDate: "2023-03-10",
	},
	{
		title: "Front End Engineer",
		company: "Foton Tech",
		image: "foton",
		url: "https://foton.tech",
		city: "Florianópolis",
		state: "Santa Catarina",
		startDate: "2021-07-21",
		endDate: "2021-12-01",
	},
	{
		title: "Front End Developer",
		company: "Insigna Consultoria",
		image: "insigna",
		url: "https://www.insignaconsultoria.com.br",
		city: "Campinas",
		state: "São Paulo",
		startDate: "2021-03-21",
		endDate: "2021-07-21",
	},
	{
		title: "Front End Developer",
		company: "Dryve Tecnologia",
		image: "dryve",
		url: "https://dryve.com.br",
		city: "Ribeirão Preto",
		state: "São Paulo",
		startDate: "2019-07-21",
		endDate: "2021-01-21",
	},
	{
		title: "Full Stack Engineer",
		company: "Datamob",
		image: "datamob",
		url: "http://datamob.com.br",
		city: "Ribeirão Preto",
		state: "São Paulo",
		startDate: "2016-07-21",
		endDate: "2019-06-21",
	},
];
